// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

#include "mongoose_glue.h"
#include "esp_spiffs.h"
#include "driver/gpio.h"

#include "esp_ota_ops.h"
#include "esp_partition.h"

#include "esp_task_wdt.h"
#include "esp_log.h"

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "sim.h"

#define WIFI_SSID "Acres of Ice"
#define WIFI_PASS "UkDfPNEj5@"

static bool s_ota_active = false;
// static esp_ota_handle_t s_ota_handle = 0;

#define LED_GPIO GPIO_NUM_8

#define PUMP_ON_GPIO  GPIO_NUM_12    
#define PUMP_OFF_GPIO GPIO_NUM_13   


static const char *TAG = "PUMP";


extern void wifi_init(const char *ssid, const char *pass);

#define TLS_CA ""
#define FIRMWARE_VERSION "1.0.2"

static struct mg_rpc *s_rpc = NULL;
static uint8_t s_qos = 1;
static char s_device_id[40];
#define DEVICE_ID "Shey"
static const char *s_topic_prefix = "mg_mqtt_dashboard";

static esp_ota_handle_t s_ota_handle = 0;
static bool s_ota_in_progress = false;

struct device_state {
  bool pump_status;            // true = ON, false = OFF
  char firmware_version[20];
};
static struct device_state s_device_state = {false, FIRMWARE_VERSION};

// struct device_state {
//   bool led_status;
//   char firmware_version[20];
// };
// static struct device_state s_device_state = {false, FIRMWARE_VERSION};

// static char *make_topic_name(char *buf, size_t len, const char *suffix) {
//   if (s_device_id[0] == '\0') {
//     mg_snprintf(s_device_id, sizeof(s_device_id), "device_%llu", mg_now());
//   }
//   mg_snprintf(buf, len, "%s/%s/%s", s_topic_prefix, s_device_id, suffix);
//   return buf;
// }

static char *make_topic_name(char *buf, size_t len, const char *suffix) {
  // FIXED DEVICE ID - NO MORE AUTO-GENERATION!
  mg_snprintf(buf, len, "%s/%s/%s", s_topic_prefix, DEVICE_ID, suffix);
  return buf;
}

static void publish_response(struct mg_connection *c, char *buf, size_t len) {
  struct mg_mqtt_opts pub_opts;
  char topic[100];
  memset(&pub_opts, 0, sizeof(pub_opts));
  pub_opts.topic = mg_str(make_topic_name(topic, sizeof(topic), "tx"));
  pub_opts.message = mg_str_n(buf, len);
  pub_opts.qos = s_qos;
  mg_mqtt_pub(c, &pub_opts);
}

// FIXED: Manual JSON without mg_xprintf
static void publish_status(struct mg_connection *c) {
  char topic[100];
  char json[256];
  struct mg_mqtt_opts pub_opts;
  
  // Manual JSON formatting (safe, no mg_xprintf)
  snprintf(json, sizeof(json),
    "{\"method\":\"status.notify\",\"params\":{\"status\":\"online\","
    "\"pump_status\":%s,\"firmware_version\":\"%s\"}}",
    s_device_state.pump_status ? "true" : "false", 
    s_device_state.firmware_version);

  memset(&pub_opts, 0, sizeof(pub_opts));
  pub_opts.topic = mg_str(make_topic_name(topic, sizeof(topic), "status"));
  pub_opts.message = mg_str(json);
  pub_opts.qos = s_qos;
  pub_opts.retain = true;
  mg_mqtt_pub(c, &pub_opts);
}

static void rpc_state_set(struct mg_rpc_req *r) {
  // Access mg_str directly using .buf and .len (standard Mongoose)
  char msg[128];
  int copy_len = (r->frame.len < sizeof(msg) - 1) ? r->frame.len : sizeof(msg) - 1;
  memcpy(msg, r->frame.buf, copy_len);  // Use .buf not .ptr
  msg[copy_len] = '\0';
  
  printf("MQTT RX: %s\n", msg);
  
  // Standard C string matching
  if (strstr(msg, "PUMP ON") != NULL) {
    printf("🚿 PUMP ON - GPIO42:1 GPIO43:0\n");
    s_device_state.pump_status = true;
    gpio_set_level(PUMP_ON_GPIO, 1);
    gpio_set_level(PUMP_OFF_GPIO, 0);
    
    // ✅ VERIFY GPIO STATES
    printf("GPIO42: %d, GPIO43: %d\n", gpio_get_level(PUMP_ON_GPIO), gpio_get_level(PUMP_OFF_GPIO));
    
    mg_rpc_ok(r, "PUMP ON");
    
  } else if (strstr(msg, "PUMP OFF") != NULL) {
    printf("⏹️ PUMP OFF - GPIO42:0 GPIO43:1\n");
    s_device_state.pump_status = false;
    gpio_set_level(PUMP_ON_GPIO, 0);
    gpio_set_level(PUMP_OFF_GPIO, 1);
    
    // ✅ VERIFY GPIO STATES
    printf("GPIO42: %d, GPIO43: %d\n", gpio_get_level(PUMP_ON_GPIO), gpio_get_level(PUMP_OFF_GPIO));
    }else {
    mg_rpc_err(r, 2, "Commands: PUMP ON | PUMP OFF");
  }
}

static void rpc_ota_upload(struct mg_rpc_req *r) {
  long ofs = mg_json_get_long(r->frame, "$.params.offset", -1);
  long tot = mg_json_get_long(r->frame, "$.params.total", -1);
  int len = 0;
  char *buf = mg_json_get_b64(r->frame, "$.params.chunk", &len);
  if (buf == NULL) {
    mg_rpc_err(r, 1, "Error processing the binary chunk.");
  } else {
    if (ofs < 0 || tot < 0) {
      mg_rpc_err(r, 1, "offset and total not set");
    } else if (ofs >= tot) {
      mg_rpc_err(r, 1, "OTA already completed, offset %ld >= total %ld", ofs, tot);
    }  else if (ofs == 0 && mg_ota_begin((size_t) tot) == false) {
      mg_rpc_err(r, 1, "mg_ota_begin(%ld) failed\n", tot);
      mg_ota_end();
    } else if (len > 0 && mg_ota_write(buf, len) == false) {
      mg_rpc_err(r, 1, "mg_ota_write(%lu) @%ld failed\n", len, ofs);
      mg_ota_end();
    }else if (ofs + len >= tot) {  // 🔥 THIS IS THE COMPLETION CHECK
     if (mg_ota_end() == false) {
        mg_rpc_err(r, 1, "mg_ota_end() failed");
      } else {
        // 🔥 CRITICAL: REBOOT HERE!
        printf("✅ OTA SUCCESS! Rebooting...\n");
        mg_rpc_ok(r, "OTA complete - rebooting");
        vTaskDelay(pdMS_TO_TICKS(1000));  // 1 second delay
        esp_restart();  // REBOOT TO NEW FIRMWARE
      }
    } else {
      mg_rpc_ok(r, "%m", MG_ESC("ok"));
    }
    mg_free(buf);
  }
}

void my_mqtt_tls_init(struct mg_connection *c) {
  bool is_tls = mg_url_is_ssl(WIZARD_MQTT_URL);
  MG_DEBUG(("%lu TLS enabled: %s", c->id, is_tls ? "yes" : "no"));
  if (is_tls) {
    struct mg_tls_opts opts = {0};
    opts.ca = mg_str(TLS_CA);
    opts.name = mg_url_host(WIZARD_MQTT_URL);
    mg_tls_init(c, &opts);
  }
}

void my_mqtt_on_connect(struct mg_connection *c, int code) {
  char topic[100];
  struct mg_mqtt_opts opts = {0};
  opts.qos = 1;
  opts.topic = mg_str(make_topic_name(topic, sizeof(topic), "rx"));
  mg_mqtt_sub(c, &opts);
  publish_status(c);
  MG_DEBUG(("%lu code %d. Subscribed to rx topic", c->id, code));
  printf("MQTT Connected! Visit https://mongoose.ws/mqtt-dashboard/\n");
}

// void my_mqtt_on_message(struct mg_connection *c, struct mg_str topic, struct mg_str data) {
//   struct mg_iobuf io = {0, 0, 0, 512};
//   struct mg_rpc_req r = {&s_rpc, NULL, mg_pfn_iobuf, &io, NULL, {data.buf, data.len}};
//   size_t clipped_len = data.len > 512 ? 512 : data.len;
  
//   printf("MQTT RX: %.*s <- %.*s\n", (int)topic.len, topic.buf, (int)clipped_len, data.buf);
  
//   mg_rpc_process(&r);
//   if (io.buf && io.len > 0) {
//     publish_response(c, (char *) io.buf, io.len);
//     publish_status(c);
//   }
//   mg_iobuf_free(&io);
// }

void my_mqtt_on_message(struct mg_connection *c, struct mg_str topic, struct mg_str data) {
  char msg[128];
  int copy_len = (data.len < sizeof(msg) - 1) ? data.len : sizeof(msg) - 1;
  memcpy(msg, data.buf, copy_len);
  msg[copy_len] = '\0';
  
  printf("MQTT RAW: %s\n", msg);
  
  // 🔥 DIRECT PUMP CONTROL - NO RPC LAYER!
  if (strstr(msg, "PUMP ON") != NULL) {
    printf("✅ PUMP ON TRIGGERED!\n");
    s_device_state.pump_status = true;
    gpio_set_level(PUMP_ON_GPIO, 1);
    gpio_set_level(PUMP_OFF_GPIO, 0);
    printf("GPIO12=%d GPIO13=%d ✅\n", gpio_get_level(PUMP_ON_GPIO), gpio_get_level(PUMP_OFF_GPIO));
    publish_status(c);
    return;  // EXIT BEFORE RPC!
  } 
  else if (strstr(msg, "PUMP OFF") != NULL) {
    printf("✅ PUMP OFF TRIGGERED!\n");
    s_device_state.pump_status = false;
    gpio_set_level(PUMP_ON_GPIO, 0);
    gpio_set_level(PUMP_OFF_GPIO, 1);
    printf("GPIO12=%d GPIO13=%d ✅\n", gpio_get_level(PUMP_ON_GPIO), gpio_get_level(PUMP_OFF_GPIO));
    publish_status(c);
    return;  // EXIT BEFORE RPC!
  }
  
  // Let RPC handle other messages (OTA)
  struct mg_iobuf io = {0, 0, 0, 512};
  struct mg_rpc_req rpc_req = {&s_rpc, NULL, mg_pfn_iobuf, &io, NULL, {data.buf, data.len}};
  mg_rpc_process(&rpc_req);
  if (io.buf && io.len > 0) {
    publish_response(c, (char *) io.buf, io.len);
    publish_status(c);
  }
  mg_iobuf_free(&io);
}


struct mg_connection *my_mqtt_connect(mg_event_handler_t fn) {
  const char *url = WIZARD_MQTT_URL;
  char topic[100], message[200];
  struct mg_mqtt_opts opts = {0};
  struct mg_connection *c;

  // Manual JSON for offline status
  snprintf(message, sizeof(message),
    "{\"method\":\"status.notify\",\"params\":{\"status\":\"offline\"}}");

  opts.clean = true;
  opts.qos = s_qos;
  opts.topic = mg_str(make_topic_name(topic, sizeof(topic), "status"));
  opts.version = 4;
  opts.retain = true;
  opts.message = mg_str(message);

  if (s_rpc == NULL) {
    //mg_rpc_add(&s_rpc, mg_str("state.set"), rpc_state_set, NULL);
    mg_rpc_add(&s_rpc, mg_str("ota.upload"), rpc_ota_upload, NULL);
  }

  if ((c = mg_mqtt_connect(&g_mgr, url, &opts, fn, NULL)) != NULL) {
    MG_DEBUG(("%lu MQTT connect initiated", c->id));
  }
  return c;
}

void app_main() {
  esp_vfs_spiffs_conf_t conf = {
    .base_path = "/spiffs",
    .max_files = 20,
    .format_if_mount_failed = true,
  };
  esp_vfs_spiffs_register(&conf);

  // wifi_init(WIFI_SSID, WIFI_PASS);
  // printf("WiFi connected, initializing Mongoose...\n");

    esp_err_t ret = sim_init();
  if (ret != ESP_OK) {
    ESP_LOGE(TAG, "SIM initialization failed");
    // System cannot work without network in SIM mode
    while (1) {
      vTaskDelay(pdMS_TO_TICKS(1000));
    }
  }else{
    ESP_LOGI(TAG, "SIM initialization succesful");
  }

  mongoose_init();

//  s_ota_active = false;
//  s_ota_handle = 0;

  gpio_set_direction(LED_GPIO, GPIO_MODE_OUTPUT);
  gpio_set_level(LED_GPIO, 0);  // LED OFF initially

  gpio_set_direction(PUMP_ON_GPIO, GPIO_MODE_OUTPUT);
  gpio_set_direction(PUMP_OFF_GPIO, GPIO_MODE_OUTPUT);
  gpio_set_level(PUMP_ON_GPIO, 0);   // Pump OFF initially
  gpio_set_level(PUMP_OFF_GPIO, 0);  // Safety ON initially

  esp_task_wdt_config_t wdt_config = {
    .timeout_ms = 15000,  // 15 seconds
    .idle_core_mask = 0,
    .trigger_panic = true
  };
  esp_task_wdt_init(&wdt_config);
  esp_task_wdt_add(NULL);

const esp_partition_t *ota_part = esp_ota_get_next_update_partition(NULL);
printf("OTA ready: %s (%lu KB)\n", ota_part->label, ota_part->size/1024);


  struct mongoose_mqtt_handlers mqtt_handlers = {
    my_mqtt_connect,
    my_mqtt_on_connect,
    my_mqtt_on_message,
  };
  mongoose_set_mqtt_handlers(&mqtt_handlers);

  printf("MQTT handlers set. Starting main loop...\n");
  for (;;) {
    mongoose_poll();
    esp_task_wdt_reset();      // 🔧 FIX: Reset watchdog every loop
    vTaskDelay(pdMS_TO_TICKS(10));  // Yield CPU
  }
}
